esphome:
  name: "sdl-lvgl"
  friendly_name: "SDL test system"
  comment: "SDL test 480px * 480px Smart Screen"

host:
  mac_address: "DC:F5:05:5A:52:45"

packages:
  # Generic configuration for ESP32 screens
# SDL has no Wi-Fi
# wifi: !include modules/base/wifi.yaml
  base: !include modules//base/base.yaml
  colors: !include modules/base/color.yaml
  fonts: !include modules/base/fonts.yaml
  images: !include modules/base/images.yaml
  time: !include modules/base/time_homeassistant.yaml
  sensors: !include modules/sensors/sensors_base-SDL.yaml
  substitutions: !include modules/base/substitutions.yaml

  # Harware description file
  hardware: !include modules/hardware/SDL-lvgl.yaml

  # This section will Update button and relay state from Home Assistant
  # Any button that has real time updates needs a section here

  # Button 2 - Standard light button with state updates
  button_1_state: !include
    file: modules/sensors/switch_or_light_button_state.yaml
    vars:
      uid: button_1
      entity_id: "light.salle_ordi"

# -------------------------------------------------------------------------
# LVGL pages and buttons
# -------------------------------------------------------------------------
lvgl:
  style_definitions:
    - id: no_checked_color
      bg_color: 0xCC5E14
      text_color: 0xB6B6B6
  theme: !include { file: modules/base/theme.yaml }
  page_wrap: true

# Boot screen
  top_layer: !include
    file: modules/screens/boot_screen.yaml
    vars:
      height: $screen_height
      width: $screen_width

# Main Page
  pages:
    - id: main_page
      layout:
        type: flex
        flex_flow: COLUMN_WRAP
      width: 100%
      bg_color: white
      bg_opa: cover
      pad_all: 5
      <<: !include
        file: modules/sections/swipe_navigation.yaml
      widgets:
        # Button 1 - Standard (double hight) internal relay button with state updates
        - button: !include
            file: modules/buttons/light_button.yaml
            vars:
              uid: button_1
              height: $button_height_single
              text: Salle Ordi
              icon: $lightbulb
              entity_id: "light.salle_ordi"
        # Button 2 - Standard script
        - button: !include
            file: modules/buttons/script_call.yaml
            vars:
              uid: button_2
              height: $button_height_single
              text: Timer 30 sec
              icon: $sec30
              entity_id: "script.30_secondes"
        # Button 3 - Standard script
        - button: !include
            file: modules/buttons/script_call.yaml
            vars: 
              uid: button_3
              height: $button_height_single
              text: Timer 45 sec
              icon: $sec45
              entity_id: "script.45_secondes"
        # Button 4 - Standard script
        - button: !include
            file: modules/buttons/script_call.yaml
            vars:
              uid: button_4
              height: $button_height_single
              text: Timer 60 sec
              icon: $sec60
              entity_id: "script.60_secondes"
        # Button 5 - Go to next page
        - button: !include
            file: modules/buttons/page_button.yaml
            vars:
              uid: button_5
              height: $button_height_single
              text: Go to clock
              icon: $arrowright
              page: "second_page"
    - id: second_page
      width: 100%
      bg_color: Black
      <<: !include
        file: modules/sections/swipe_navigation.yaml      
      widgets:
          # Outer Clock Container
          - obj:
              height: 470
              width: 470
              align: center
              pad_all: 4
              bg_color: Black
              border_width: 0
              widgets:
              - meter:
                  height: 100%
                  width: 100%
                  align: center
                  bg_color: White

                  scales:
                    # Minor ticks
                    - ticks:
                        width: 2
                        count: 61
                        length: 10
                        color: Black
                      range_from: 0
                      range_to: 60
                      angle_range: 360
                      rotation: 270

                      # Minuite hand
                      indicators:
                        - line:
                            id: minute_hand
                            width: 3
                            color: Black
                            r_mod: -1
                    # Major ticks
                    - angle_range: 330
                      rotation: 300
                      range_from: 1
                      range_to: 12
                      ticks:
                        width: 3
                        count: 12
                        length: 20
                        color: Black

                    # Hour hand
                    - angle_range: 360
                      rotation: 270
                      range_from: 0
                      range_to: 720
                      indicators:
                        - line:
                            id: hour_hand
                            width: 4
                            color: Black
                            r_mod: -40

                    # Second hand
                    - angle_range: 360
                      rotation: 270
                      range_from: 0
                      range_to: 60
                      indicators:
                        - line:
                            id: second_hand
                            width: 2
                            color: Red
                            r_mod: -10