---
esphome:
  on_boot:
    priority: -100
    then:
      - delay: $boot_screen_delay
      - lvgl.widget.hide: boot_screen

api:
  encryption:
    key: !secret keyguiton480

logger:
#  level: info
#  logs:
#    i2c.idf: info
#    touchscreen: info
#    scheduler: none

lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  on_idle:
    timeout: $touchscreen_idle_timeout
    then:
      - logger.log: "LVGL is idle"
      - if:
          condition:
            - lambda: 'return id(brightness_mode).state == "Day";'
          then:
            - light.turn_on:
                id: display_backlight
                brightness: ${touchscreen_daytime_brightness}
      - if:
          condition:
            - lambda: 'return id(brightness_mode).state == "Evening";'
          then:
            - light.turn_on:
                id: display_backlight
                brightness: ${touchscreen_nighttime_brightness}
      - if:
          condition:
            - lambda: 'return id(brightness_mode).state == "Night";'
          then:
            - light.turn_off: display_backlight
            - lvgl.pause:
                show_snow: true

# Wake on screen touch
touchscreen:
    on_touch:
      then:
        - logger.log: "LVGL is active"
        - lvgl.resume
        - lvgl.widget.redraw
        - if:
            condition:
              - lambda: 'return id(brightness_mode).state == "Day";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: ${touchscreen_daytime_brightness}
        - if:
            condition:
              - lambda: 'return id(brightness_mode).state == "Evening";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: ${touchscreen_nighttime_brightness}
        - if:
            condition:
              - lambda: 'return id(brightness_mode).state == "Night";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: ${touchscreen_nighttime_brightness}

select:
  - platform: template
    name: "Brightness mode"
    id: brightness_mode
    icon: mdi:television-shimmer
    optimistic: true
    options:
      - Day
      - Evening
      - Night
    initial_option: Day
    on_value:
      then:
        - lvgl.resume
        - lvgl.widget.redraw
        - if:
            condition:
              - lambda: 'return id(brightness_mode).state == "Day";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: ${touchscreen_daytime_brightness}
        - if:
            condition:
              - lambda: 'return id(brightness_mode).state == "Evening";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: ${touchscreen_nighttime_brightness}
        - if:
            condition:
              - lambda: 'return id(brightness_mode).state == "Night";'
            then:
              - light.turn_on:
                  id: display_backlight
                  brightness: ${touchscreen_nighttime_brightness}