# Substitution variables used through the codebase
substitutions:
  lightbulb:         "\U000F0335"
#  ceiling_light:     "\U000F0769"
#  lamp:              "\U000F06B5"
#  floor_lamp:        "\U000F08DD"
#  string_lights:     "\U000F12BA"
#  track_light:       "\U000F0914"
#  bulkhead_light:    "\U000F1A2F"
#  led_strip:         "\U000F07D6"
#  coach_lamp:        "\U000F1020"
#  ceiling_fan_light: "\U000F1798"
#  bed:               "\U000F02E3"
#  sunny:             "\U000F05A8"
  sec30:             "\U000F0D06"
  sec45:             "\U000F1B12"
  sec60:             "\U000F160B"
  arrowright:        "\U000F06C2"
  arrowleft:         "\U000F06C1"
  number1:           "\U000F15CB"
  number5:           "\U000F0B3E"
  playpause:         "\U000F040E"
  numberminus1:      "\U000F1052"
  home:              "\U000F02DC"
  previous:          "\U000F0731"
  next:              "\U000F0734"
  shuffle_icon:      "\U000F049F"
  noshuffle_icon:    "\U000F049E"
  previous_track:    "\U000F04AE"
  next_track:        "\U000F04AD"
  volume:            "\U000F057E"
  volumeup:          "\U000F075D"
  volumedown:        "\U000F075E"

  red: "0xFF0000"
  icon_font: light40
  icon_font_small: light24
  text_font: roboto24
  text_font_big: light75
  text_color: white
  bg_color: black
  button_on_color: "ep_orange"
  button_off_color: "very_dark_gray"
  icon_on_color: "yellow"
  icon_off_color: "gray"
  label_on_color: "white"
  label_off_color: "gray"
  button_text_color: "white"
  button_height_single: '99px'
  button_height_double: '208px'
  button_width: '150px'
  button_width_4column: '111px'
  button_width_2column: '230px'
  touchscreen_idle_timeout: "30s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_daytime_brightness_idle: "35%"
  touchscreen_nighttime_brightness: "35%"
  # Boot screen configuration
  boot_screen_delay: 30s

  # Set Night mode  at Mightnight
  screen_night_hour: '0'
  screen_night_minute: '0'

  # Set Day mode at 5:30am
  screen_day_hour: '5'
  screen_day_minute: '30'

  # Set Evening mode at 7:30pm
  screen_evening_hour: '19'
  screen_evening_minute: '30'

  # Screen Size
  screen_height: '480px'
  screen_width: '480px'
  sdl_height: '480'
  sdl_width: '480'